### ISSUE TITLE
"Remove Window Frame" fails on Atom 1.21.0-beta0 on Windows 10 x64

### ISSUE THREAD

**Issue by Dragory** [sindrets/atom-title-bar-replacer#10]
The following error gets logged to the console:
```
Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\<username>\AppData\Local\atom\app-1.21.0-beta0\resources\app\src\main-process\atom-window.js'
```

I checked the path and the only thing under the `app` folder is a folder called `apm`. Should I extract app.asar, or did Atom 1.21.0 change things too much for the that feature to work for now?

**Comment by sindrets** [comment]
@Dragory oh no. Are they returning to ASAR packaging? This is sad news for the window frame remover. I have a window frame remover that works with the current Beta setup, because this is the way it used to be before Atom 1.17. However it is dramatically slower than the current implementation for several reasons:
 1. It requires the asar file to be extracted, then modified, then repacked. Extraction and repacking can take up to several minutes depending on CPU and disk write speeds.
 2. It's gonna mean I have to require the asar package as a dependency. This will increase the number of node modules required from the current 1, to 96, which will in turn dramatically increase activation time.

Due to the reasons above, I will not prioritize doing anything about this until the stable build catches up to this practice. I will therefore close this issue as it doesn't apply to the current stable build of Atom.

BUT, I have a temporary solution for you. I have written a batch file which does exactly what the asar implementation of the window frame remover would do. I will attach it to this comment. Just unzip and run it from anywhere on your computer. It should not require admin rights, and it will automatically locate your most recent installation of Atom (including betas). I just tested it on my machine, and it works with Atom beta 1.21.
[_windowFrameRemover.zip](https://github.com/sindrets/atom-title-bar-replacer/files/1299437/_windowFrameRemover.zip)

**Comment by Dragory** [comment]
Thank you!

**Comment by sindrets** [comment]
@Dragory I forgot to mention: the batch file require the [asar npm package](https://www.npmjs.com/package/asar) to be installed globally. If you have Node, it can be installed by running the following command:
```
npm install asar -g
```
