### ISSUE TITLE
Atom 1.53.0-nightly1 adds option to disable the native title bar

### ISSUE THREAD

**Issue by 1011025m** [sindrets/atom-title-bar-replacer#62]
Since [1.53.0-nightly1](https://github.com/atom/atom/compare/13e6412e...10dfeb8c) you can change the Atom title bar to "hidden". I believe this change will stay so the extracting process may not be needed soon. Just a little change I want to mention. :D

**Comment by sindrets** [comment]
@1011025m Thank you for bringing my attention to this. I removed the patch process entirely in v2.0.0

**Comment by 1011025m** [comment]
Nice! Thank you for updating it :D

Do you plan to automate the settings change (i.e. for the option where you have to turn the topbar to hidden), or is it already implemented?

**Comment by sindrets** [comment]
@1011025m No, I don't plan to automate the settings change, because I don't think packages should mess with settings that aren't their own. Besides, unlike the patching, you can change this setting once and never have to worry about it again. I explain where to find the setting in the readme, and I think that's enough.
