### ISSUE TITLE
Javascript's getBoundingClientRect() always returns wrong position

### ISSUE THREAD

**Issue by Encipheric** [sindrets/atom-title-bar-replacer#66]
The cause is entirely due to div element "title-bar-replacer"

#### Why is it the cause:
Deleting it makes getBoundingClientRect() work properly again

## Steps to reproduce:
- Use latest Atom and latest package version
- Use inspect element and inspect "atom-workspace-axis"
- Right click and select **Store as global variable**
- Go to console and use **getBoundingClientRect** on that element

## What is wrong:
Its position should exactly match X and Y of top most tab, but instead it is offset by the title bar replacer element.
All elements that depend on getBoundingClientRect() will instead cascade into another wrong direction.
Any packages that rely on this function will break due to this problem.
Any settings configuration that utilizes this title bar in this package will cause this issue.

**Comment by sindrets** [comment]
@Encipheric  Hm, I think you have misunderstood something here.

> Its position should exactly match X and Y of top most tab,

This is not true. `Element.getBoundingClientRect()` returns the position and dimensions of an element relative to the viewport. So when the DOMRect of the `atom-workspace-axis` element looks something like this:

```json
{"x":0,"y":33,"width":1654,"height":518,"top":33,"right":1654,"bottom":551,"left":0}
```

It's because that is actually the position the element has relative to the viewport.

> but instead it is offset by the title bar replacer element.

Yes, because it is literally below the title bar replacer element, so that is what the offset should be.

> All elements that depend on getBoundingClientRect() will instead cascade into another wrong direction.

No, this will not happen if the DOMRect is used correctly. 

> Any packages that rely on this function will break due to this problem.
> Any settings configuration that utilizes this title bar in this package will cause this issue.

I suspect that - if you have an example of this - that the package is using the DOMRect incorrectly.

Please take a look at [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

**Comment by m4heshd** [comment]
> No, this will not happen if the DOMRect is used correctly.

Except it can. Facing the same issue right now on an Electron app. Nothing related to this repo but the exact same issue. All the coordinates are offset by the height of title bar. `getBoundingClientRect()` can be super unreliable. @ghost was probably onto something.
